# Generated by Django 4.2.21 on 2025-05-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_add_job_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['-scheduled_date']},
        ),
        migrations.AlterField(
            model_name='interview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
